In [1]:
import pandas as pd

df = pd.read_pickle('my_dataset.pkl')
display(df)

      time/h           polymer  enzyme  crystallinity xc
0          0       [*]CC([*])C  PETase         44.470000
1         24       [*]CC([*])C  PETase         45.163529
2         48       [*]CC([*])C  PETase         47.259905
3         72       [*]CC([*])C  PETase         49.642818
4         96       [*]CC([*])C  PETase         51.104824
...      ...               ...     ...               ...
2095     384  [*]CC([*])(C)C#N  Cut190         31.785915
2096     408  [*]CC([*])(C)C#N  Cut190         32.959726
2097     432  [*]CC([*])(C)C#N  Cut190         34.478069
2098     456  [*]CC([*])(C)C#N  Cut190         36.753803
2099     480  [*]CC([*])(C)C#N  Cut190         37.719457

[2100 rows x 4 columns]

In [5]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in /home/bt719957/.local/lib/python3.10/site-packages (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/bt719957/.local/lib/python3.10/site-packages (from scikit-learn) (3.2.0)
Requirement already satisfied: scipy>=1.5.0 in /home/bt719957/.local/lib/python3.10/site-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in /home/bt719957/.local/lib/python3.10/site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: numpy<2.0,>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.26.1)

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 

df = pd.read_pickle('my_dataset.pkl')
display(df)
df_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
len(df), len(df_train), len(df_test)

      time/h           polymer  enzyme  crystallinity xc
0          0       [*]CC([*])C  PETase         44.470000
1         24       [*]CC([*])C  PETase         45.163529
2         48       [*]CC([*])C  PETase         47.259905
3         72       [*]CC([*])C  PETase         49.642818
4         96       [*]CC([*])C  PETase         51.104824
...      ...               ...     ...               ...
2095     384  [*]CC([*])(C)C#N  Cut190         31.785915
2096     408  [*]CC([*])(C)C#N  Cut190         32.959726
2097     432  [*]CC([*])(C)C#N  Cut190         34.478069
2098     456  [*]CC([*])(C)C#N  Cut190         36.753803
2099     480  [*]CC([*])(C)C#N  Cut190         37.719457

[2100 rows x 4 columns]

(2100, 1680, 420)

In [2]:
print(df_train)

      time/h                            polymer    enzyme  crystallinity xc
577      240                      [*]CC([*])CCC      PET2         32.948983
1699     456  [*]CC([*])OC(=O)CCCCCCCCCCCCCCCCC    PETase         65.448486
107       48                        [*]CC([*])C       HiC         48.245316
757       24                   [*]CC([*])CC(C)C       FsC         23.308917
65        48                        [*]CC([*])C  ThC_Cut1         48.248377
...      ...                                ...       ...               ...
960      360                  [*]CCCCCCCC([*])C       HiC         52.844887
905       48                  [*]CCCCCCCC([*])C  ThC_Cut1         33.352808
1096      96                        [*]CC([*])O       TfH         44.400187
235       96                       [*]CC([*])CC       LCC         37.911528
1061     264                        [*]CC([*])O    PETase         55.368177

[1680 rows x 4 columns]

In [3]:
print(df_test)

      time/h                          polymer  enzyme  crystallinity xc
1601     120  [*]CC([*])OC(=O)CCCCCCCCCCCCCCC     FsC         39.593638
1268     192      [*]CC([*])OC(=O)CCCCCCCCCCC  PETase         25.503092
587      480                    [*]CC([*])CCC    PET2         46.220431
950      120                [*]CCCCCCCC([*])C     HiC         37.829518
1613     408  [*]CC([*])OC(=O)CCCCCCCCCCCCCCC     FsC         58.281447
...      ...                              ...     ...               ...
386      192                     [*]CC([*])CC    PET5         44.926688
1397     264      [*]CC([*])OC(=O)CCCCCCCCCCC     FsC         27.294951
2093     336                 [*]CC([*])(C)C#N  Cut190         27.995008
1452      72      [*]CC([*])OC(=O)CCCCCCCCCCC  Cut190         16.857453
1520     192  [*]CC([*])OC(=O)CCCCCCCCCCCCCCC     TfH         45.127199

[420 rows x 4 columns]